# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alpelliz <alpelliz@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/15 14:01:52 by alpelliz          #+#    #+#              #
#    Updated: 2024/01/17 11:15:53 by alpelliz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #



SRCS			= phonebook.cpp utils.cpp
OBJS			= $(SRCS:.c=.o)
TARGET			= Phonebook

CC				= c++
RM				= rm -f
CFLAGS			= -Wall -Wextra -Werror

all: $(TARGET)

$(NAME) : all

$(TARGET): $(SRCS)
	@$(CC) $(SRCS) $(CFLAGS) -o $(TARGET)
	@printf "Ready.\n"

clean:
	@$(RM) $(TARGET)
	@printf 'clean: phonebook executable succesfully removed\n'

re: clean all

fclean: clean
	@printf 'fclean: target removed\n'

.PHONY:			all clean fclean re%
